CREATE DATABASE LOCADORA;

USE LOCADORA;

CREATE TABLE  CLIENTES(
	ID_CLIENTE INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(50),
    ENDERECO VARCHAR(75),
    CPF VARCHAR(14),
    TELEFONE VARCHAR(11)
);

CREATE TABLE GENEROS(
	ID_GENERO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_GENERO VARCHAR(30)
);

CREATE TABLE FILMES(
	ID_FILME INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(75),
    TITULO_ORIGINAL VARCHAR(75),
    DIRETOR VARCHAR(50),
    ANO_LANÇAMENTO VARCHAR(4),
    VALOR_DIARIA NUMERIC(15,2),
    IMAGEM VARCHAR(50),
    SINOPSE BLOB,
    ID_GENERO INTEGER    
);

CREATE TABLE EMPRESTIMOS(
    ID_EMPRESTIMO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INTEGER,
    ID_FILME INTEGER,
    DATA DATE,
    DATA_DEVOLLUCAO DATE    
);



